<?xml version="1.0"?>
  	<robot  name="dhm" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<!-- These values must be entered manually -->
	<!-- Average BMI = 22. If above, enter 1, else enter 0 -->
	<xacro:property name="bodyHeight" value="1.83" />
	<xacro:property name="bodyMass" value="88" />
	<xacro:property name="BMI" value="${bodyMass/(bodyHeight*bodyHeight)}" />
	<xacro:property name="isBMIgreaterThanAverage" value="0"/>
	<!-- From now on, nothing should be changed in the file -->

	<xacro:property name="PI" value="3.1415926535897931"/>

	<!-- Joint maximal velocity (guessed) -->
	<xacro:property name="maxVelJoint" value="3.0" />

	<!-- Scaling factor for joint maximal torque capacity (real capacity = factor * average human capacity)-->
	<xacro:property name="forceCapacity" value="1.0" />

	<!-- Joint dynamic properties -->
	<xacro:property name="jointDamping" value="0.1" />
	<xacro:property name="jointFriction" value="0.1" />

	<!-- Define length of body segments from total body bodyHeight -->

    <xacro:property name="ankleHeight" value="${bodyHeight*0.04}" />
	<xacro:property name="kneeHeight" value="${bodyHeight*0.28}" />
	<xacro:property name="hipHeight" value="${bodyHeight*0.53}" />
	<xacro:property name="shoulderHeight" value="${bodyHeight*0.82}" />
	<xacro:property name="hipWidth" value="${bodyHeight*0.105}" />
	<xacro:property name="armSpan" value="${bodyHeight*1.09}" />
	<xacro:property name="handLength" value="${bodyHeight*0.1}" />
	<xacro:property name="footLength" value="${bodyHeight*0.152}" />


	
	<xacro:property name="S5_L5_x" value="-0.000836" />
	<xacro:property name="S5_hip_x" value="0" />

	<xacro:property name="L5_T8_x" value="${ 0.0}" />
	<xacro:property name="T8_CSJ_y" value="0" />


    <xacro:property name="S5_L5" value="${0.06*bodyHeight}" />
	<xacro:property name="L5_T8" value="${0.18*bodyHeight}" />
	<xacro:property name="T8_C7" value="${0.095*bodyHeight}" />
	<xacro:property name="CSJ_C7" value="${0.05*bodyHeight}" />
	<xacro:property name="T8_CSJ" value="${T8_C7 - CSJ_C7}" />
	<xacro:property name="C7_C1" value="${0.055*bodyHeight}" />
	<xacro:property name="C1_headtop" value="${0.08*bodyHeight}" />
	<xacro:property name="headbase_headtop" value="${1.1*C1_headtop}" />


    <xacro:property name="shoulder_elbow" value="${bodyHeight*0.19}" />
	<xacro:property name="elbow_wrist" value="${bodyHeight*0.15}" />
	<xacro:property name="CSJ_shoulder" value="${0.5*armSpan - shoulder_elbow - elbow_wrist - handLength}" />


	<xacro:property name="S5_hip_horizontal" value="${0.5*hipWidth}" />


	<!-- Define thickness of body segment from BMI -->
	<xacro:property name="slimBMI" value="17" />
	<xacro:property name="normBMI" value="22" />
	<xacro:property name="fatBMI" value="40" />
	<xacro:property name="slimAlpha" value="0.9" />
	<xacro:property name="normAlpha" value="1.0" />
	<xacro:property name="fatAlpha" value="1.3" />
	
	<xacro:if value="${isBMIgreaterThanAverage == 1}">
		<xacro:property name="alpha" value="${1 + (fatAlpha  - normAlpha) * (BMI - normBMI) / (fatBMI - normBMI)}" />-->
	</xacro:if>
	<xacro:if value="${isBMIgreaterThanAverage == 0}">
		<xacro:property name="alpha" value="${1 - (normAlpha - slimAlpha) * (normBMI - BMI) / (normBMI - slimBMI)}" />-->
	</xacro:if>

	<!-- Define body segments shapes -->
	<!-- For collision shapes, pelvis, lumbarspine, and thoracicspine is scaled by a factor collision_XXX_factor to enable arms along body without collision issues with the torso -->
	<xacro:property name="collision_width_factor" value="0.7"/>
  <xacro:property name="collision_height_factor" value="0.7"/>
  <xacro:property name="collision_depth_factor" value="0.7"/>

	<xacro:property name="hip_thickness" value="${alpha*0.08}" />


	<xacro:property name="pelvis_length" value="${S5_L5 + hip_thickness}" /> 
	<xacro:property name="pelvis_width" value="${hipWidth + 0.7*hip_thickness + alpha*0.11}" />
	<xacro:property name="pelvis_depth" value="${2*alpha*0.11}" />

	<xacro:property name="lumbarspine_length" value="${L5_T8}" />
	<xacro:property name="lumbarspine_width" value="${hipWidth+alpha*0.105}" />
	<xacro:property name="lumbarspine_depth" value="${2*alpha*0.105}" />

	<xacro:property name="thoracicspine_length" value="${T8_C7}" />
	<xacro:property name="thoracicspine_width" value="${2*0.7*CSJ_shoulder+alpha*0.10}" />
	<xacro:property name="thoracicspine_depth" value="${2*alpha*0.10}" />

	<xacro:property name="neck_length" value="${C7_C1}" />
	<xacro:property name="neck_radius" value="${alpha*0.045}" />

	<xacro:property name="head_length" value="${headbase_headtop}" />
	<xacro:property name="head_radius" value="${0.1}" />

	<xacro:property name="clavicular_length" value="${CSJ_shoulder}" />
	<xacro:property name="clavicular_radius" value="${alpha*0.06}" />

	<xacro:property name="arm_length" value="${shoulder_elbow}" />
	<xacro:property name="arm_radius" value="${alpha*0.05}" />

	<xacro:property name="forearm_length" value="${elbow_wrist}" />
	<xacro:property name="forearm_radius" value="${alpha*0.04}" />

	<xacro:property name="palm_length" value="${0.5*handLength}" />
	<xacro:property name="palm_width" value="${2*alpha*0.04}" />
	<xacro:property name="palm_depth" value="${2*alpha*0.015}" />
	
	<xacro:property name="fingers_length" value="${0.5*handLength}" />
	<xacro:property name="fingers_width" value="${palm_width}" />
	<xacro:property name="fingers_depth" value="${palm_depth}" />

	<xacro:property name="hand_length" value="${handLength}" />
	<xacro:property name="hand_width" value="${2*alpha*0.04}" />
	<xacro:property name="hand_depth" value="${2*alpha*0.015}" />

	<!-- Define mass normalization value and segment masses -->
	<xacro:property name="massNorm" value="${-0.0426 + 1.00096*bodyMass + 0.00058*bodyHeight*100}" />

	<xacro:property name="lowertorso_mass" value="${bodyMass * (-7.498 + 0.0976*bodyMass + 0.04896*bodyHeight*100) / massNorm}" />
	<xacro:property name="middletorso_mass" value="${bodyMass * (7.181 + 0.2234*bodyMass - 0.0663*bodyHeight*100) / massNorm}" />
	<xacro:property name="uppertorso_mass" value="${bodyMass * (8.2144 + 0.1862*bodyMass - 0.0584*bodyHeight*100) / massNorm}" />
	<xacro:property name="pelvis_mass" value="${lowertorso_mass}" />
	<xacro:property name="lumbarspine_mass" value="${middletorso_mass}" />
	<xacro:property name="thoracicspine_mass" value="${(1.0-0.1)*uppertorso_mass}" />
	<xacro:property name="neckandhead_mass" value="${bodyMass * (1.296 + 0.0171*bodyMass + 0.0143*bodyHeight*100) / massNorm}" />
	<xacro:property name="neck_mass" value="${0.1*neckandhead_mass}" />
	<xacro:property name="head_mass" value="${0.9*neckandhead_mass}" />
	<xacro:property name="clavicular_mass" value="${0.05*uppertorso_mass}" />
	<xacro:property name="arm_mass" value="${bodyMass * (0.25 + 0.03012*bodyMass - 0.0027*bodyHeight*100) / massNorm}" />
	<xacro:property name="forearm_mass" value="${bodyMass * (0.3185 + 0.01445*bodyMass - 0.00114*bodyHeight*100) / massNorm}" />
	<xacro:property name="hand_mass" value="${bodyMass * (-0.1165 + 0.0036*bodyMass + 0.00175*bodyHeight*100) / massNorm}" />
	<xacro:property name="palm_mass" value="${0.7*hand_mass}" />
	<xacro:property name="fingers_mass" value="${0.3*hand_mass}" />
	<xacro:property name="thigh_mass" value="${bodyMass * (-2.649 + 0.1463*bodyMass + 0.0137*bodyHeight*100) / massNorm}" />
	<xacro:property name="shank_mass" value="${bodyMass * (-1.592 + 0.03616*bodyMass + 0.0121*bodyHeight*100) / massNorm}" />
	<xacro:property name="foot_mass" value="${bodyMass * (-0.829 + 0.0077*bodyMass + 0.0073*bodyHeight*100) / massNorm}" />

	<!-- Macro which computes a shape (box or cylinder) inertia -->
	<!-- The lengths Lx, Ly and Lz are in the segment inertial frame (and not in the segment base frame, i.e. joint frame) -->
	<!-- For the cylinder, the cylinder axis is along Z -->
	<xacro:macro name="box_inertia" params="m Lx Ly Lz">
		<inertia ixx="${1/12 * m * (Ly*Ly + Lz*Lz)}" ixy="0" ixz="0" iyy="${1/12 * m * (Lx*Lx + Lz*Lz)}" iyz="0" izz="${1/12 * m * (Lx*Lx + Ly*Ly)}" />
	</xacro:macro>
	<xacro:macro name="cylinder_inertia" params="m L r">
		<inertia ixx="${1/12 * m * (3*r*r + L*L)}" ixy="0" ixz="0" iyy="${1/12 * m * (3*r*r + L*L)}" iyz="0" izz="${1/2 * m * r*r}" />
	</xacro:macro>			
	<xacro:macro name="sphere_inertia" params="m r">
		<inertia ixx="${2/5 * m * r*r}" ixy="0" ixz="0" iyy="${2/5 * m * r*r}" iyz="0" izz="${2/5 * m * r*r}" />
	</xacro:macro>	

	<!-- URDF only accepts 1DoF joint. 
	A joint with several DoFs can be implemented as a succession of 1DoF-joint linked by "virtual" bodies.
	These "virtual" bodies must have a physical mass for the simulation to run. 
	They are represented as spheres with a mass and vitualRadius defined hereafter. 
	The mass depends of the masses of the adjacent bodies to avoind numerical issues in the dynamic simulation --> 
	<xacro:property name="virtual_radius" value="0.01" />
	<xacro:macro name="virtual_body" params="name m">
		<link name="${name}">
			<inertial>
				<mass value="${m}" />
				<origin xyz="0 0 0" rpy="0 0 0" />
				<xacro:sphere_inertia m="${m}" r="${virtual_radius}"/>
			</inertial>
		</link>
	</xacro:macro>

	<!-- Materials -->
	<material name="blue">
		<color rgba="0 0 0.8 1"/>
	</material>

	<!-- Define bodies -->

	<link name="pelvis">
		<visual>
			<geometry>
				<box size="${pelvis_depth} ${pelvis_width} ${pelvis_length}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${pelvis_length/2-hip_thickness}"/>
			<material name="blue" />
		</visual>
		<collision>
			<geometry>
				<box size="${collision_depth_factor*pelvis_depth} ${collision_width_factor*pelvis_width} ${collision_height_factor*pelvis_length}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${pelvis_length/2-hip_thickness}"/>
		</collision>
		<inertial>
			<mass value="${0.7*pelvis_mass}" />
			<origin rpy="0 0 0" xyz="0 0 ${pelvis_length/2-hip_thickness}"/>
			<xacro:box_inertia m="${0.7*pelvis_mass}" Lx="${pelvis_depth}" Ly="${pelvis_width}" Lz="${pelvis_length}"/>
		</inertial>
	</link>

	<xacro:virtual_body name="body_L5_1" m="${0.1*pelvis_mass}"/>
	<xacro:virtual_body name="body_L5_2" m="${0.1*lumbarspine_mass}"/>

	<link name="lumbar_spine">
		<visual>
			<geometry>
				<box size="${lumbarspine_depth}  ${lumbarspine_width} ${lumbarspine_length}"/>
			</geometry>
 			<origin rpy="0 0 0" xyz="0 0 ${lumbarspine_length/2}"/>
			<material name="blue" />
		</visual>
		<collision>
			<geometry>
				<box size="${collision_depth_factor*lumbarspine_depth}  ${collision_width_factor*lumbarspine_width} ${collision_height_factor*lumbarspine_length}"/>			
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${lumbarspine_length/2}"/>
		</collision>
		<inertial>
			<mass value="${0.8*lumbarspine_mass}" />
			<origin rpy="0 0 0" xyz="0 0 ${lumbarspine_length/2}"/>
			<xacro:box_inertia m="${0.8*lumbarspine_mass}" Lx="${lumbarspine_depth}" Ly="${lumbarspine_width}" Lz="${lumbarspine_length}"/>
		</inertial>
	</link>

	<xacro:virtual_body name="body_T8_1" m="${0.1*lumbarspine_mass}"/>
	<xacro:virtual_body name="body_T8_2" m="${0.1*thoracicspine_mass}"/>

	<link name="thoracic_spine">
		<visual>
			<geometry>
				<box size="${thoracicspine_depth} ${thoracicspine_width} ${thoracicspine_length}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${thoracicspine_length/2}"/>
			<material name="blue" />
		</visual>
		<collision>
			<geometry>
				<box size="${collision_depth_factor*thoracicspine_depth} ${collision_width_factor*thoracicspine_width} ${collision_height_factor*thoracicspine_length}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${thoracicspine_length/2}"/>
		</collision>
		<inertial>
			<mass value="${0.65*thoracicspine_mass}" />
			<origin rpy="0 0 0" xyz="0 0 ${thoracicspine_length/2}" />
			<xacro:box_inertia m="${0.65*thoracicspine_mass}" Lx="${thoracicspine_depth}" Ly="${thoracicspine_width}" Lz="${thoracicspine_length}"/>
		</inertial>
	</link>


	
	<xacro:virtual_body name="body_T4_right_clavicular" m="${0.1*thoracicspine_mass}"/>

	<link name="right_clavicular">
		<visual>
			<geometry>
				<cylinder length="${clavicular_length}" radius="${clavicular_radius}"/> 
			</geometry>
			<origin  rpy="0 0 0" xyz="0 0 ${CSJ_shoulder/2}"/>
			<material name="blue" />
		</visual>
		<inertial>
			<mass value="${0.9*clavicular_mass}" />
			<origin  rpy="0 0 0" xyz="0 0 ${CSJ_shoulder/2}"/>
			<xacro:cylinder_inertia m="${0.9*clavicular_mass}" L="${clavicular_length}" r="${clavicular_radius}" />
		</inertial>
	</link>

	<xacro:virtual_body name="body_right_shoulder_1" m="${0.1*clavicular_mass}"/>
	<xacro:virtual_body name="body_right_shoulder_2" m="${0.1*arm_mass}"/>

	<link name="right_arm">
		<visual>
			<geometry>
				<cylinder length="${arm_length}" radius="${arm_radius}"/>    
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${arm_length/2}"/>
			<material name="blue" />
		</visual>
		<collision>
			<geometry>
				<cylinder length="${arm_length}" radius="${arm_radius}"/>      
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${arm_length/2}"/>
		</collision>
		<inertial>
			<mass value="${0.8*arm_mass}" />
			<origin rpy="0 0 0" xyz="0 0 ${arm_length/2}"/>
			<xacro:cylinder_inertia m="${0.8*arm_mass}" L="${arm_length}" r="${arm_radius}" />
		</inertial>
	</link>

	<xacro:virtual_body name="body_right_elbow" m="${0.1*arm_mass}"/>

	<link name="right_forearm">
		<visual>
			<geometry>
				<cylinder length="${forearm_length}" radius="${forearm_radius}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${forearm_length/2}"/>
			<material name="blue" />
		</visual>
		<collision>
			<geometry>
				<cylinder length="${forearm_length}" radius="${forearm_radius}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${forearm_length/2}"/>
		</collision>
		<inertial>
			<mass value="${0.9*forearm_mass}" />
			<origin rpy="0 0 0" xyz="0 0 ${forearm_length/2}"/>
			<xacro:cylinder_inertia m="${0.9*forearm_mass}" L="${forearm_length}" r="${forearm_radius}" />
		</inertial>
	</link>

	<xacro:virtual_body name="body_right_wrist" m="${0.1*forearm_mass}"/>

	<link name="right_hand">
		<visual>
			<geometry>
				<box size="${hand_width} ${hand_depth} ${hand_length}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${hand_length/2}"/>
			<material name="blue" />
		</visual>
		<collision>
			<geometry>
				<box size="${hand_width} ${hand_depth} ${hand_length} "/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${hand_length/2}"/>
		</collision>
		<inertial>
			<mass value="${hand_mass}" />
			<origin rpy="0 0 0" xyz="0 0 ${hand_length/2}" />
			<xacro:box_inertia m="${hand_mass}" Lx="${hand_width}" Ly="${hand_depth}" Lz="${hand_length}"/>
		</inertial>
	</link>

	
<joint name="right_hand_fixed" type="fixed">
   <origin rpy="0 0 0 " xyz="0.0 0.0 ${hand_length / 2}"/>
   <child link="right_hand_gripper"/>
   <parent link="right_hand"/>
   <axis use_parent_model_frame="1" xyz="0 0 0"/>
   <dynamics damping="0" friction="0" spring_reference="0" spring_stiffness="0"/>
 </joint>
 <link name="right_hand_gripper">
   <inertial>
     <origin xyz="0 0 0"/>
     <mass value="0.000001"/>
     <inertia ixx="0.000001" ixy="0.000001" ixz="0.000001" iyy="0.000001" iyz="0.000001" izz="0.000001"/>
   </inertial>
 </link>

<xacro:virtual_body name="body_T4_left_clavicular" m="${0.1*thoracicspine_mass}"/>

<link name="left_clavicular">
		<visual>
			<geometry>
				<cylinder length="${clavicular_length}" radius="${clavicular_radius}"/> 
			</geometry>
			<origin  rpy="0 0 0" xyz="0 0 ${CSJ_shoulder/2}"/>
			<material name="blue" />
		</visual>
		<inertial>

			<mass value="${0.9*clavicular_mass}" />
			<origin  rpy="0 0 0" xyz="0 0 ${CSJ_shoulder/2}"/>
			<xacro:cylinder_inertia m="${0.9*clavicular_mass}" L="${clavicular_length}" r="${clavicular_radius}" />
		</inertial>
	</link>


<xacro:virtual_body name="body_left_shoulder_1" m="${0.1*clavicular_mass}"/>
<xacro:virtual_body name="body_left_shoulder_2" m="${0.1*arm_mass}"/>

 <link name="left_arm">
		<visual>
			<geometry>
				<cylinder length="${arm_length}" radius="${arm_radius}"/>    
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${arm_length/2}"/>
			<material name="blue" />
		</visual>
		<collision>
			<geometry>
				<cylinder length="${arm_length}" radius="${arm_radius}"/>      
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${arm_length/2}"/>
		</collision>
		<inertial>
			<mass value="${0.8*arm_mass}" />
			<origin rpy="0 0 0" xyz="0 0 ${arm_length/2}"/>>
			<xacro:cylinder_inertia m="${0.8*arm_mass}" L="${arm_length}" r="${arm_radius}" />
		</inertial>
	</link>

	<xacro:virtual_body name="body_left_elbow" m="${0.1*arm_mass}"/>

	<link name="left_forearm">
		<visual>
			<geometry>
				<cylinder length="${forearm_length}" radius="${forearm_radius}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${forearm_length/2}"/>
			<material name="blue" />
		</visual>
		<collision>
			<geometry>
				<cylinder length="${forearm_length}" radius="${forearm_radius}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${forearm_length/2}"/>
		</collision>
		<inertial>
			<mass value="${0.9*forearm_mass}" />
			<origin rpy="0 0 0" xyz="0 0 ${forearm_length/2}"/>
			<xacro:cylinder_inertia m="${0.9*forearm_mass}" L="${forearm_length}" r="${forearm_radius}" />
		</inertial>
	</link>

	<xacro:virtual_body name="body_left_wrist" m="${0.1*forearm_mass}"/>

	<link name="left_hand">
		<visual>
			<geometry>
				<box size="${hand_width} ${hand_depth} ${hand_length}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${hand_length/2}"/>
			<material name="blue" />
		</visual>
		<collision>
			<geometry>
				<box size="${hand_width} ${hand_depth} ${hand_length}"/>
			</geometry>
			<origin rpy="0 0 0" xyz="0 0 ${hand_length/2}"/>
		</collision>
		<inertial>
			<mass value="${hand_mass}" />
			<origin rpy="0 0 0" xyz="0 0 ${hand_length/2}" />
			<xacro:box_inertia m="${hand_mass}" Lx="${hand_width}" Ly="${hand_depth}" Lz="${hand_length}"/>
		</inertial>
	</link>




	<!-- Define joints -->


	<!-- Back joints -->
	<joint name="lumbarspine_X" type="revolute">
		<parent link="pelvis"/>
		<child link="body_L5_1"/>
		<axis xyz="1 0 0"/>
		<origin xyz="0 0 ${bodyHeight/2}"/>
		<limit effort="${155*forceCapacity}" lower="-0.175" upper="0.175" velocity="${maxVelJoint}"/>
		<!-- <limit effort="${155*forceCapacity}" lower="-0.7" upper="0.7" velocity="${maxVelJoint}"/> -->
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="lumbarspine_Y" type="revolute">
		<parent link="body_L5_1"/>
		<child link="body_L5_2"/>
		<axis xyz="0 1 0"/>
		<origin xyz="0 0 0"/>
		<!-- <limit effort="${228*forceCapacity}" lower="-0.175" upper="0.175" velocity="${maxVelJoint}"/> -->
		<limit effort="${228*forceCapacity}" lower="-0.175" upper="1.57" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="lumbarspine_Z" type="revolute">
		<parent link="body_L5_2"/>
		<child link="lumbar_spine"/>
		<axis xyz="0 0 1"/>
		<origin xyz="0 0 0"/>
		<limit effort="${65*forceCapacity}" lower="-0.262" upper="0.262" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="thoracicspine_X" type="revolute">
		<parent link="lumbar_spine"/>
		<child link="body_T8_1"/>
		<axis xyz="1 0 0"/>
		<origin xyz="${L5_T8_x} 0 ${L5_T8}"/>
		<limit effort="${155*forceCapacity}" lower="-0.175" upper="0.175" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="thoracicspine_Y" type="revolute">
		<parent link="body_T8_1"/>
		<child link="body_T8_2"/>
		<axis xyz="0 1 0"/>
		<origin xyz="0 0 0"/>
		<limit effort="${228*forceCapacity}" lower="-0.175" upper="0.175" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="thoracicspine_Z" type="revolute">
		<parent link="body_T8_2"/>
		<child link="thoracic_spine"/>
		<axis xyz="0 0 1"/>
		<origin xyz="0 0 0"/>
		<limit effort="${65*forceCapacity}" lower="-0.262" upper="0.262" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<!-- Right arm joints -->
	<joint name="right_clavicular_X" type="revolute">
    <!-- flexion (elevation) -->   
		<parent link="thoracic_spine"/>
		<child link="body_T4_right_clavicular"/>
		<axis xyz="1 0 0"/>
		<origin xyz="0 ${-T8_CSJ_y} ${T8_CSJ}" rpy="${PI/2} 0 0"/>
		<limit effort="${105*forceCapacity}" lower="${-0.15}" upper="${0.15}" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="right_clavicular_Y" type="revolute">
    <!-- abduction -->
		<parent link="body_T4_right_clavicular"/>
		<child link="right_clavicular"/>
		<axis xyz="0 1 0"/>
		<origin xyz="0 0 0"/>
		<limit effort="${107*forceCapacity}" lower="${-0.5}" upper="${0.5}" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="right_shoulder_X" type="revolute">
    <!-- abduction -->
		<parent link="right_clavicular"/>
		<child link="body_right_shoulder_1"/>
		<axis xyz="1 0 0"/>
		<origin xyz="0 0 ${CSJ_shoulder}"/>
		<limit effort="${69*forceCapacity}" lower="-1.571" upper="${PI}" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="right_shoulder_Y" type="revolute">
    <!-- flexion -->
		<parent link="body_right_shoulder_1"/>
		<child link="body_right_shoulder_2"/>
		<axis xyz="0 1 0"/>
		<origin xyz="0 0 0"/>
		<limit effort="${90*forceCapacity}" lower="${-PI/2}" upper="${PI/2}" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="right_shoulder_Z" type="revolute">
    <!-- rotation -->
		<parent link="body_right_shoulder_2"/>
		<child link="right_arm"/>
		<axis xyz="0 0 1"/>
		<origin xyz="0 0 0"/>
		<limit effort="${51*forceCapacity}" lower="-1.658" upper="1.396" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="right_elbow_Y" type="revolute">
    <!-- flexion -->
		<parent link="right_arm"/>
		<child link="body_right_elbow"/>
		<axis xyz="0 1 0"/>
		<origin xyz="0 0 ${shoulder_elbow}"/>
		<!-- <limit effort="${75*forceCapacity}" lower="${-PI/10}" upper="2.531" velocity="${maxVelJoint}"/> -->
		<limit effort="${75*forceCapacity}" lower="0" upper="2.531" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="right_elbow_Z" type="revolute">
    <!-- pronosupination -->
		<parent link="body_right_elbow"/>
		<child link="right_forearm"/>
		<axis xyz="0 0 1"/>
		<origin xyz="0 0 0"/>
		<limit effort="${13*forceCapacity}" lower="${-PI/2}" upper="${PI/2}" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="right_wrist_X" type="revolute">
    <!-- flexion -->
		<parent link="right_forearm"/>
		<child link="body_right_wrist"/>
		<axis xyz="1 0 0"/>
		<origin xyz="0 0 ${elbow_wrist}"/>
		<limit effort="${10*forceCapacity}" lower="-1.0" upper="1.0" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="right_wrist_Y" type="revolute">
    <!-- abduction -->
		<parent link="body_right_wrist"/>
		<child link="right_hand"/>
		<axis xyz="0 1 0"/>
		<origin xyz="0 0 0"/>
		<limit effort="${11*forceCapacity}" lower="-0.6" upper="0.6" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="left_clavicular_X" type="revolute">
    <!-- flexion (elevation) --> 
		<parent link="thoracic_spine"/>
		<child link="body_T4_left_clavicular"/>
		<axis xyz="1 0 0"/>
		<origin xyz="0 0 ${T8_CSJ}" rpy="${-PI/2} 0 0"/>
		<limit effort="${105*forceCapacity}" lower="${-0.15}" upper="${0.15}" velocity="${maxVelJoint}"/>
		<!-- <limit effort="${105*forceCapacity}" lower="${-0.5}" upper="${0.5}" velocity="${maxVelJoint}"/> -->
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="left_clavicular_Y" type="revolute">
    <!-- abduction -->
		<parent link="body_T4_left_clavicular"/>
		<child link="left_clavicular"/>
		<axis xyz="0 1 0"/>
		<origin xyz="0 0 0"/>
		<!-- <limit effort="${107*forceCapacity}" lower="${-1.0}" upper="${1.0}" velocity="${maxVelJoint}"/> -->
		<limit effort="${107*forceCapacity}" lower="${-0.5}" upper="${0.5}" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>


	<joint name="left_shoulder_X" type="revolute">
    <!-- abduction -->
		<parent link="left_clavicular"/>
		<child link="body_left_shoulder_1"/>
		<axis xyz="1 0 0"/>
		<origin xyz="0 0 ${CSJ_shoulder}"/>
		<limit effort="${69*forceCapacity}" lower="${-PI}" upper="1.571" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="left_shoulder_Y" type="revolute">
    <!-- flexion -->
		<parent link="body_left_shoulder_1"/>
		<child link="body_left_shoulder_2"/>
		<axis xyz="0 1 0"/>
		<origin xyz="0 0 0"/>
		<limit effort="${90*forceCapacity}" lower="${-PI/2}" upper="${2*PI/3}" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="left_shoulder_Z" type="revolute">
    <!-- rotation -->
		<parent link="body_left_shoulder_2"/>
		<child link="left_arm"/>
		<axis xyz="0 0 1"/>
		<origin xyz="0 0 0"/>
		<limit effort="${51*forceCapacity}" lower="-1.658" upper="1.396" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="left_elbow_Y" type="revolute">
    <!-- flexion -->
		<parent link="left_arm"/>
		<child link="body_left_elbow"/>
		<axis xyz="0 1 0"/>
		<origin xyz="0 0 ${shoulder_elbow}"/>
		<!-- <limit effort="${75*forceCapacity}" lower="${-PI/10}" upper="2.531" velocity="${maxVelJoint}"/> -->
		<limit effort="${75*forceCapacity}" lower="0" upper="2.531" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="left_elbow_Z" type="revolute">
    <!-- pronosupination -->
		<parent link="body_left_elbow"/>
		<child link="left_forearm"/>
		<axis xyz="0 0 1"/>
		<origin xyz="0 0 0"/>
		<limit effort="${13*forceCapacity}" lower="${-PI/2}" upper="${PI/2}" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="left_wrist_X" type="revolute">
    <!-- flexion -->
		<parent link="left_forearm"/>
		<child link="body_left_wrist"/>
		<axis xyz="1 0 0"/>
		<origin xyz="0 0 ${elbow_wrist}"/>
		<limit effort="${10*forceCapacity}" lower="-1.0" upper="1.0" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>

	<joint name="left_wrist_Y" type="revolute">
    <!-- abduction -->
		<parent link="body_left_wrist"/>
		<child link="left_hand"/>
		<axis xyz="0 1 0"/>
		<origin xyz="0 0 0"/>
		<limit effort="${11*forceCapacity}" lower="-0.6" upper="0.6" velocity="${maxVelJoint}"/>
		<dynamics damping="${jointDamping}" friction="${jointFriction}"/>
	</joint>


	
</robot>
